require:
  - solidus_dev_support/rubocop

inherit_gem:
  solidus_dev_support: .rubocop.yml

AllCops:
  Exclude:
    - spec/dummy/**/*
    - vendor/**/*

Gemspec/OrderedDependencies:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false
